export const rows = [
    {
      id: 1,
      name: "Henry",
      mail: "hen@gmail.com",
      phone: "0753976922",
      action: "Request",
    },
    {
      id: 2,
      name: "peter",
      mail: "hen@gmail.com",
      phone: "0753976922",
      action: "Request",
    },
    {
        id: 3,
        name: "Mark",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },
      {
        id: 4,
        name: "Paul",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },
      {
        id: 4,
        name: "Paul",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },
      {
        id: 4,
        name: "Paul",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },    {
        id: 4,
        name: "Paul",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },
      {
        id: 4,
        name: "Paul",
        mail: "hen@gmail.com",
        phone: "0753976922",
        action: "Request",
      },
  ];
